import { StyleSheet } from 'react-native';

import { theme } from '@/constants/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.bg,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: theme.colors.bg,
  },
  haloOne: {
    position: 'absolute',
    top: 70,
    left: -60,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: '#FFE8DF',
  },
  haloTwo: {
    position: 'absolute',
    right: -70,
    top: 220,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: '#FFF1E8',
  },
  header: {
    paddingHorizontal: 22,
    paddingTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFECE7',
  },
  brandWrap: {
    flex: 1,
    paddingHorizontal: 14,
  },
  brand: {
    fontFamily: theme.fonts.primary,
    color: theme.colors.lineStrong,
    fontSize: 22,
    lineHeight: 26,
  },
  brandSub: {
    marginTop: 2,
    fontFamily: theme.fonts.body,
    color: theme.colors.textSub,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  content: {
    paddingHorizontal: 22,
    paddingTop: 18,
    paddingBottom: 30,
  },
  stageCard: {
    borderRadius: 34,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 22,
    backgroundColor: '#FFFDF9',
    overflow: 'hidden',
    ...theme.shadow.card,
    shadowOpacity: 0.2,
  },
  stageBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#FFFDF9',
  },
  stageRing: {
    position: 'absolute',
    left: -80,
    right: -80,
    top: 120,
    height: 280,
    borderRadius: 160,
    borderWidth: 18,
    borderColor: 'rgba(212, 168, 114, 0.28)',
  },
  stageGlow: {
    position: 'absolute',
    top: 140,
    left: 46,
    right: 46,
    height: 260,
    borderRadius: 130,
    backgroundColor: '#FFE6C9',
  },
  messageBubble: {
    alignSelf: 'flex-start',
    maxWidth: '86%',
    borderRadius: 24,
    backgroundColor: theme.colors.white,
    paddingHorizontal: 18,
    paddingVertical: 16,
    shadowColor: '#D9BBB1',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 6,
  },
  messageLabel: {
    fontFamily: theme.fonts.body,
    fontSize: 12,
    lineHeight: 16,
    color: theme.colors.lineStrong,
    fontWeight: '700',
  },
  messageText: {
    marginTop: 6,
    fontFamily: theme.fonts.body,
    color: theme.colors.textMain,
    fontSize: 17,
    lineHeight: 28,
    fontWeight: '500',
  },
  avatarWrap: {
    alignSelf: 'center',
    marginTop: 28,
    width: 242,
    alignItems: 'center',
  },
  avatarPressable: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  characterShell: {
    width: 220,
    height: 258,
    borderRadius: 44,
    overflow: 'hidden',
    backgroundColor: 'rgba(255, 249, 244, 0.92)',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.7)',
    shadowColor: '#D39F94',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 8,
  },
  characterLottie: {
    width: '100%',
    height: '100%',
  },
  purrText: {
    marginTop: 10,
    fontFamily: theme.fonts.primary,
    color: theme.colors.lineStrong,
    fontSize: 18,
    lineHeight: 22,
  },
  heartColumn: {
    position: 'absolute',
    right: 10,
    top: 24,
    alignItems: 'center',
  },
  heart: {
    fontSize: 18,
    color: theme.colors.primary,
  },
  heartSecondary: {
    marginTop: 4,
    fontSize: 14,
    color: '#FFC1BC',
  },
  stageFooter: {
    marginTop: 20,
    alignItems: 'center',
  },
  stageTitle: {
    fontFamily: theme.fonts.primary,
    fontSize: 24,
    lineHeight: 28,
    color: theme.colors.textMain,
  },
  stageHint: {
    marginTop: 8,
    fontFamily: theme.fonts.body,
    fontSize: 14,
    lineHeight: 22,
    color: theme.colors.textSub,
    fontWeight: '500',
    textAlign: 'center',
  },
  quickActionRow: {
    marginTop: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    columnGap: 10,
  },
  quickActionButton: {
    flex: 1,
    borderRadius: 22,
    backgroundColor: '#FFF0EB',
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    columnGap: 6,
    paddingHorizontal: 10,
  },
  quickActionText: {
    fontFamily: theme.fonts.primary,
    fontSize: 14,
    lineHeight: 18,
    color: theme.colors.lineStrong,
  },
  soundCard: {
    marginTop: 18,
    borderRadius: 28,
    backgroundColor: '#FFF7F2',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 18,
    ...theme.shadow.card,
    shadowOpacity: 0.12,
  },
  soundCardTitle: {
    fontFamily: theme.fonts.primary,
    fontSize: 22,
    lineHeight: 26,
    color: theme.colors.textMain,
  },
  soundCardSubtitle: {
    marginTop: 6,
    fontFamily: theme.fonts.body,
    fontSize: 13,
    lineHeight: 20,
    color: theme.colors.textSub,
    fontWeight: '500',
  },
  soundPresetGrid: {
    marginTop: 14,
    rowGap: 10,
  },
  soundPresetCard: {
    borderRadius: 22,
    backgroundColor: theme.colors.white,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 12,
  },
  soundPresetCardActive: {
    borderWidth: 1.5,
    borderColor: '#F3B2A9',
    backgroundColor: '#FFF1EC',
  },
  soundPresetIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  soundPresetTextWrap: {
    flex: 1,
  },
  soundPresetName: {
    fontFamily: theme.fonts.primary,
    fontSize: 16,
    lineHeight: 20,
    color: theme.colors.textMain,
  },
  soundPresetSubtitle: {
    marginTop: 2,
    fontFamily: theme.fonts.body,
    fontSize: 12,
    lineHeight: 18,
    color: theme.colors.textSub,
    fontWeight: '500',
  },
  feedCard: {
    marginTop: 18,
    borderRadius: 28,
    backgroundColor: theme.colors.white,
    paddingHorizontal: 18,
    paddingVertical: 18,
    ...theme.shadow.card,
    shadowOpacity: 0.14,
  },
  feedTitle: {
    fontFamily: theme.fonts.primary,
    fontSize: 20,
    lineHeight: 24,
    color: theme.colors.textMain,
  },
  feedBubble: {
    marginTop: 12,
    borderRadius: 20,
    backgroundColor: '#FFF4EF',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  feedBubbleText: {
    fontFamily: theme.fonts.body,
    color: theme.colors.textMain,
    fontSize: 15,
    lineHeight: 24,
    fontWeight: '500',
  },
  voiceButton: {
    marginTop: 18,
    borderRadius: 30,
    backgroundColor: '#FFE0DE',
    paddingHorizontal: 18,
    paddingVertical: 18,
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 14,
  },
  voiceIconWrap: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: theme.colors.lineStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  voiceTextWrap: {
    flex: 1,
  },
  voiceTitle: {
    fontFamily: theme.fonts.primary,
    fontSize: 22,
    lineHeight: 26,
    color: theme.colors.textMain,
  },
  voiceSubtitle: {
    marginTop: 4,
    fontFamily: theme.fonts.body,
    fontSize: 13,
    lineHeight: 20,
    color: theme.colors.textSub,
    fontWeight: '500',
  },
});
