import { StyleSheet } from 'react-native';

import { theme } from '@/constants/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.bg,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: theme.colors.bg,
  },
  glowTop: {
    position: 'absolute',
    top: -120,
    right: -70,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: '#FFF0E4',
  },
  glowBottom: {
    position: 'absolute',
    left: -80,
    bottom: 120,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: '#FFF3ED',
  },
  content: {
    paddingHorizontal: 22,
    paddingTop: 8,
    paddingBottom: 184,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 22,
  },
  headerButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFECEA',
  },
  headerIconButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandWrap: {
    flex: 1,
    paddingHorizontal: 14,
  },
  brand: {
    fontFamily: theme.fonts.primary,
    color: theme.colors.lineStrong,
    fontSize: 20,
    lineHeight: 24,
  },
  title: {
    marginTop: 24,
    fontFamily: theme.fonts.primary,
    fontSize: 34,
    lineHeight: 42,
    color: theme.colors.lineStrong,
  },
  subtitle: {
    marginTop: 8,
    fontFamily: theme.fonts.body,
    fontSize: 15,
    lineHeight: 24,
    color: theme.colors.textSub,
    fontWeight: '600',
  },
  titleSection: {
    paddingHorizontal: 22,
    marginTop: 12,
  },
  // Card stack — full width, no horizontal margin
  stackSection: {
    marginTop: 14,
    overflow: 'hidden',
  },
  bottomSection: {
    paddingHorizontal: 22,
    paddingTop: 16,
    paddingBottom: 8,
    gap: 10,
  },
  stackWrap: {
    marginTop: 24,
    paddingTop: 18,
    paddingBottom: 12,
    justifyContent: 'flex-start',
  },
  previewCard: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1,
  },
  previewCardClip: {
    overflow: 'hidden',
    borderRadius: 28,
  },
  previewCardInner: {
    shadowOpacity: 0,
  },
  activeCard: {
    zIndex: 2,
  },
  // Card: rounded corners clip everything, overflow hidden kept
  companionCard: {
    borderRadius: 28,
    overflow: 'hidden',
    backgroundColor: '#E9C79B',
    ...theme.shadow.card,
    shadowOpacity: 0.18,
  },
  heroStage: {
    overflow: 'hidden',
    backgroundColor: '#F1D0A4',
  },
  heroLottie: {
    position: 'absolute',
  },
  placeholderBadge: {
    position: 'absolute',
    left: 18,
    top: 18,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(255,255,255,0.9)',
  },
  placeholderBadgeText: {
    fontFamily: theme.fonts.primary,
    fontSize: 13,
    lineHeight: 16,
    color: theme.colors.lineStrong,
  },
  favoriteButton: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#E9877C',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.24,
    shadowRadius: 14,
    elevation: 8,
  },
  infoPanel: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: 'rgba(255,255,255,0.97)',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 22,
  },
  infoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    columnGap: 12,
  },
  identityWrap: {
    flex: 1,
    minWidth: 0,
  },
  // Smaller name & label
  companionName: {
    fontFamily: theme.fonts.primary,
    fontSize: 22,
    lineHeight: 26,
    color: '#1F1B1A',
  },
  companionEnglish: {
    marginTop: 2,
    fontFamily: theme.fonts.accent,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 1.2,
    color: theme.colors.lineStrong,
  },
  tagGroup: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    columnGap: 8,
  },
  // Smaller circular tags: 70 → 54
  tag: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  tagText: {
    fontFamily: theme.fonts.primary,
    fontSize: 10,
    lineHeight: 14,
    textAlign: 'center',
  },
  description: {
    marginTop: 12,
    fontFamily: theme.fonts.body,
    fontSize: 14,
    lineHeight: 22,
    color: theme.colors.textMain,
    fontWeight: '500',
  },
  descriptionScroll: {
    marginTop: 0,
    maxHeight: 88,
  },
  swipeHintRow: {
    marginTop: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    columnGap: 8,
  },
  swipeHintText: {
    fontFamily: theme.fonts.body,
    fontSize: 13,
    lineHeight: 18,
    color: theme.colors.textSub,
    fontWeight: '600',
  },
  pagination: {
    flexDirection: 'row',
    justifyContent: 'center',
    columnGap: 8,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#E8D8D2',
  },
  paginationDotActive: {
    width: 24,
    backgroundColor: theme.colors.lineStrong,
  },
  primaryButtonDock: {
    position: 'absolute',
    left: 22,
    right: 22,
    bottom: 12,
  },
  primaryButton: {
    minHeight: 68,
    borderRadius: 36,
    backgroundColor: theme.colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    columnGap: 10,
    ...theme.shadow.card,
    shadowOpacity: 0.2,
  },
  primaryButtonText: {
    fontFamily: theme.fonts.primary,
    fontSize: 26,
    lineHeight: 30,
    color: theme.colors.textMain,
  },
});
