import { StyleSheet } from 'react-native';

import { theme } from '@/constants/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.bg,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: theme.colors.bg,
  },
  glowTop: {
    position: 'absolute',
    top: -86,
    right: -42,
    width: 292,
    height: 292,
    borderRadius: 146,
    backgroundColor: 'rgba(255, 234, 213, 0.72)',
  },
  glowBottom: {
    position: 'absolute',
    left: -94,
    bottom: 122,
    width: 264,
    height: 264,
    borderRadius: 132,
    backgroundColor: 'rgba(255, 241, 234, 0.8)',
  },
  content: {
    paddingHorizontal: 22,
    paddingTop: 8,
    paddingBottom: 184,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 28,
    paddingTop: 8,
  },
  headerButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FDEAE8',
  },
  headerIconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.44)',
  },
  brandWrap: {
    flex: 1,
    paddingHorizontal: 16,
  },
  brand: {
    fontFamily: theme.fonts.primary,
    color: theme.colors.lineStrong,
    fontSize: 22,
    lineHeight: 28,
  },
  title: {
    marginTop: 10,
    fontFamily: theme.fonts.primary,
    fontSize: 38,
    lineHeight: 46,
    color: theme.colors.lineStrong,
  },
  subtitle: {
    marginTop: 10,
    fontFamily: theme.fonts.body,
    fontSize: 16,
    lineHeight: 26,
    color: theme.colors.textSub,
    fontWeight: '600',
  },
  titleSection: {
    paddingHorizontal: 28,
    marginTop: -8,
  },
  // Card stack — full width, no horizontal margin
  stackSection: {
    marginTop: 5,
    overflow: 'hidden',
    marginLeft: 18,
    marginRight: 18,
    paddingHorizontal: 18,
  },
  bottomSection: {
    paddingHorizontal: 26,
    paddingTop: 10,
    paddingBottom: 16,
    gap: 12,
  },
  stackWrap: {
    marginTop: 4,
    paddingTop: 18,
    paddingBottom: 12,
    justifyContent: 'flex-start',
  },
  previewCard: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1,
  },
  previewCardClip: {
    overflow: 'hidden',
    borderRadius: 28,
  },
  previewCardInner: {
    shadowOpacity: 0,
  },
  activeCard: {
    zIndex: 2,
  },
  // Card: rounded corners clip everything, overflow hidden kept
  companionCard: {
    marginHorizontal: 0,
    borderRadius: 28,
    overflow: 'hidden',
    backgroundColor: '#F4D5AA',
    ...theme.shadow.card,
    shadowColor: '#E4C2B0',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.16,
    shadowRadius: 28,
    elevation: 12,
  },
  heroStage: {
    overflow: 'hidden',
    backgroundColor: '#F6DDB9',
  },
  heroLottie: {
    position: 'absolute',
  },
  placeholderBadge: {
    position: 'absolute',
    left: 18,
    top: 18,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(255,255,255,0.9)',
  },
  placeholderBadgeText: {
    fontFamily: theme.fonts.primary,
    fontSize: 13,
    lineHeight: 16,
    color: theme.colors.lineStrong,
  },
  favoriteButton: {
    position: 'absolute',
    top: 22,
    right: 20,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#FF8F96',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#F2A7A4',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 20,
    elevation: 9,
  },
  infoPanel: {
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 34,
    backgroundColor: 'rgba(255,255,255,0.98)',
    paddingHorizontal: 24,
    paddingTop: 6,
    paddingBottom: 6,
    minHeight: 44,
  },
  infoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    columnGap: 14,
  },
  identityWrap: {
    flex: 1,
    minWidth: 0,
    paddingRight: 8,
  },
  // Smaller name & label
  companionName: {
    fontFamily: theme.fonts.primary,
    fontSize: 24,
    lineHeight: 30,
    color: '#1F1B1A',
  },
  companionEnglish: {
    marginTop: 4,
    fontFamily: theme.fonts.accent,
    fontSize: 13,
    lineHeight: 16,
    letterSpacing: 1.5,
    color: theme.colors.lineStrong,
  },
  tagGroup: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    columnGap: 10,
  },
  // Smaller circular tags: 70 → 54
  tag: {
    width: 46,
    height: 46,
    borderRadius: 33,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  tagText: {
    fontFamily: theme.fonts.primary,
    fontSize: 10,
    lineHeight: 10,
    textAlign: 'center',
    fontWeight: '600',
  },
  description: {
    marginTop: 1,
    fontFamily: theme.fonts.body,
    fontSize: 15,
    lineHeight: 30,
    color: '#58433C',
    fontWeight: '500',
  },
  descriptionScroll: {
    marginTop: 0,
    maxHeight: 120,
    paddingBottom: 12,
  },
  swipeHintRow: {
    marginTop: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    columnGap: 10,
  },
  swipeHintText: {
    fontFamily: theme.fonts.body,
    fontSize: 14,
    lineHeight: 20,
    color: '#9B857D',
    fontWeight: '600',
  },
  pagination: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    columnGap: 10,
  },
  paginationDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#E9D9D2',
  },
  paginationDotActive: {
    width: 34,
    height: 12,
    borderRadius: 999,
    backgroundColor: theme.colors.lineStrong,
  },
  primaryButtonDock: {
    position: 'absolute',
    left: 22,
    right: 22,
    bottom: 12,
  },
  primaryButton: {
    minHeight: 82,
    borderRadius: 41,
    backgroundColor: '#FF8E93',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    columnGap: 12,
    ...theme.shadow.card,
    shadowColor: '#E6C6B5',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 11,
  },
  primaryButtonText: {
    fontFamily: theme.fonts.primary,
    fontSize: 30,
    lineHeight: 34,
    color: theme.colors.textMain,
  },
});
